### ISSUE TITLE
Category on NSObject for injecting dependencies?

### ISSUE THREAD

**Issue by eraserhd** [kiwi-bdd/Kiwi#168]
I have a category that I use for injecting dependencies.  For example:

[[[controllerUnderTest theMockFor:@"_button"] should] receive:@selector(setTintColor:)]

This looks up the type of _button, creates a null mock for it, sets it, and returns the mock.  It was originally called "dependencyCalled:".  There's a variant called "theMockFor:ofType:" for cases where you need to mock a superclass of the slot's type.

I'd like to contribute this to Kiwi, but not sure how this fits into the project's style.  Maintainer's thoughts?

Thanks!
-Jason

**Comment by modocache** [comment]
Thanks again for this, @eraserhd! If you still think this would be useful, feel free to open a pull request. @sharplet and I are doing some spring cleaning so I'll close this for now. :)
