### ISSUE TITLE
Testing of block evaluation

### ISSUE THREAD

**Issue by yas375** [kiwi-bdd/Kiwi#183]
Hi everyone!
I'm covering MKNetworkKit with Unit tests and I'm using Kiwi for this. I decided to test that completion blocks can be evaluated. For now I use a BOOL variable which is changed inside completion block and I'm testing that this value will be changed.

``` obj-c
context(@"when successfull", ^{
    it(@"should call completion block", ^{
        BOOL completionBlockCalled = NO;
        MKNetworkOperation *operation = [[MKNetworkOperation alloc] init];
        [operation addCompletionHandler:^(MKNetworkOperation *completedOperation) {
            completionBlockCalled = YES;
        }];
        [operation run];
        [[expectFutureValue(theValue(completionBlockCalled)) shouldEventually] beTrue];
    });
 });
```

It's a simplified version. And real code can be found (here)[https://github.com/MugunthKumar/MKNetworkKit/blob/0b7abddf4d5063df9f922a8a4bbcb803d916195a/MKNetworkKit-Tests/MKNetworkKit-Tests/MKNetworkEngineSpec.m#L71-L113].

It solves my task. But I think that it will be cool to be able to write something like this:

``` obj-c
[[theBlock(myCompletionBlock) shouldEventually] beEvaluated];
```

Thanks in advance.

p.s. comments and any advices regarding my test code are very welcome! =)

**Comment by trimmurrti** [comment]
Sorry for necroposting. I'm implementing that feature for my own use. Would anyone be interested in that 
feature?

What would the preferred syntax be? At the moment I created a separate proxy block class, that intercepts block messages. The syntax I'm thinking of is:
id block = proxy(^{ ... });
[[block should] beEvaluated];

[object performBlock:block];

Also, wanted to ask, what are the Kiwi policies on testing the inheritance in xctest? Duplication or abstract test case?
Also, should I merge proxy block with KWBlock? In my opinion it's not obvious, but the maintainers opinion would be greatly appreciated.
