### ISSUE TITLE
Leak when setting message expectations in iOS tests

### ISSUE THREAD

**Issue by sjmadsen** [kiwi-bdd/Kiwi#254]
[Edit: looks like the leak is from setting message expectations, not stubs. See my comment below from May 14.]

I have a set of examples that test a singleton. I want to put it in a known state at the beginning of each example, so I stub out the `sharedInstance` method and return a fresh instance in a `beforeEach()` block, then nil the instance in an `afterEach()` block. The instance itself is held in a `__block` variable within the context.

I've traced through the Kiwi code and I see that the return value for the stub is retained, which makes sense. The docs say that stubs are cleared at the end of each example, but it doesn't appear that the return value of the stub is released when this happens.

I've added code in the before/after blocks to verify that those are called. I've also added code in the init/dealloc methods of the class. `init` is called, as expected, but not `dealloc`.

If I remove the stub, the leak disappears, but of course my examples that depend on the stub fail.

**Comment by dueckes** [comment]
This appears to be related to: https://github.com/kiwi-bdd/Kiwi/issues/454
My experiences suggest any should call on an object leads to it being retained.

Like joekain, this has lead to some nasty situations related to notification observers being retained and firing in subsequent tests.

**Comment by glentregoning** [comment]
#667 has a proposed fix which in my testing addresses the issue by releasing verifiers after running an example.

**Comment by modocache** [comment]
Thanks for the report, @sjmadsen! I'll close this issue to focus the discussion on pull request #667.
