### ISSUE TITLE
Warning if no evaluated tests in context or describe

### ISSUE THREAD

**Issue by davidquon** [kiwi-bdd/Kiwi#282]
It'd be nice to have a warning if `context` or `describe` blocks don't have any evaluated tests.  We had a bunch of tests like below that we thought were getting executed properly but the tests were not evaluated unless there is an `it` in the `context` or `describe`.  It would be nice to have a warning for these situations to know that the test was not written properly.
```
describe(@"unit7Image", ^{
    [[ABAppearance.unit7Image should] beKindOfClass:imgClass];
});
```

**Comment by modocache** [comment]
This would be great. We may be able to reference https://github.com/orta/vigilant in the implementation. Feel free to open a pull request if you think this would still be nice to have, although I think this might be better as a separate repository.
