### ISSUE TITLE
Add +anyInstance

### ISSUE THREAD

**Issue by supermarin** [kiwi-bdd/Kiwi#295]
This is a feature from RSpec that I find very useful. It should reduce some lines of mocking in tests, here's the concrete use case:

``` objc
it(@"caches mappings", ^{
        
        [[[Car anyInstance] should] receive:@selector(mappings) withCount:1];
        
        [Car create:@{ @"hp": @150 }];
        [Car create:@{ @"make": @"Ford" }];
        [Car create:@{ @"hp": @150 }];
});
    
```

**Comment by modocache** [comment]
This would be really cool -- I'd actually like to see this on OCMock or another mocking framework. I'd also like to see Kiwi's mocking features extracted into their own library.

For now, I don't think anyone's up to working on such a large feature, though, so I'll close this.
