### ISSUE TITLE
Feature request: Focused specs (as Cedar does)

### ISSUE THREAD

**Issue by stanislaw** [kiwi-bdd/Kiwi#297]
Hello,

It would be nice to have a support for Focused specs: I mark a spec I am currently working on as 'current' or 'wip' or 'fit' and it makes Kiwi to bypass all other specs when running a test suite.

Of course you know that Cedar already has it implemented and it is described in its [README page,  Focused specs](https://github.com/pivotal/cedar) - it does exactly what I'm describing here.

Also, I've just reviewed [this comment](https://github.com/allending/Kiwi/issues/176#issuecomment-11181885) by @luisobo and now I see that together with my another issue https://github.com/allending/Kiwi/issues/289, he catched them both in a single comment.

Thanks!

**Comment by kevinwo** [comment]
Why is changing the code not a good way of implementing focused specs? In my mind, it's a far better user experience to "it -> fit" than to have to specify file name and line number. I've tried using @jerrymarino's plugin, which looks fantastic, but unfortunately currently crashes Xcode 6 when attempting to run a focused spec, or hangs without completion when attempting to run a focused file.

**Comment by jerrymarino** [comment]
@kevinwo checkout the thread #236 which has a discussion about why we didn't add support for focusing specs by changing the source code. 

There was an [issue](#597) when using Kiwi on Yosemite that caused a hang. I'd recommend updating Kiwi and making sure you're build includes this fix.

The [Xcode plugin](https://github.com/jerrymarino/CedarShortcuts) just sets the environment variable `KW_SPEC` to indicate to Kiwi the focused spec before running the test suite. There isn't any known crashes caused by plugin alone.

**Comment by kevinwo** [comment]
Thanks @jerrymarino! The explanation in #236 makes sense. However, I still experience a crash on running a single focused spec with the plugin, and for a focused file I see a report of 0 tests being run. I just now went to open an issue on the plugin GitHub page, but do not see the option to do so.

I'm using Xcode 6.4 on Yosemite 10.10.4, and have tried using the plugin with both the podspec version of Kiwi (from 6 months ago it looks like from GitHub) and the current git codebase on master (3 months ago), both to no avail. I'm curious to see if you encounter the same issue with the example project I've posted up here:

https://github.com/kevinwo/KiwiSpecPluginIssueReproduce

**Comment by marklarr** [comment]
There really should just be a built in way for Kiwi to do this. All plugin/terminal solutions that I've tried have been flaky at best. Sadly, running the whole test suite still ends up being faster.

**Comment by marklarr** [comment]
Changing the scheme to have an environment variable is all fine and dandy, but I feel like I'm _more likely_ to accidentally forget about that, and it's more time consuming.

**Comment by kevinwo** [comment]
I agree with @marklarr. One way or another, this should be a stable core feature of Kiwi.
