### ISSUE TITLE
Kiwi raises EXC_BAD_ACCESS exception on expectedFutureValue

### ISSUE THREAD

**Issue by prometedor** [kiwi-bdd/Kiwi#300]
Hi guys, could you please examine this crash?

http://stackoverflow.com/questions/16894261/kiwi-asynchronous-test-raises-exc-bad-access

I dont know whats going on inside, but looks for me it should work.
If you need more info I am ready to give you.

**Comment by modocache** [comment]
Thanks for the report, @prometedor! Sorry we couldn't get to this very quickly. I'm going to close this, if this issue still affects you after three years, I'd recommend you try @Inferis's workaround.
