### ISSUE TITLE
Randomize test run order

### ISSUE THREAD

**Issue by adamyanalunas** [kiwi-bdd/Kiwi#310]
It would be nice if there was an option, enabled by default, to randomize the order of tests run in a spec. This would help enforce the concept that unit tests should be able to be run individually, at any moment, so long as their before and after blocks are executed.

To make things more interesting it'd be great if a failing test was run first in the suite so that you don't have to wait for the rest of the tests to finish.

**Comment by modocache** [comment]
This would be great, and I'd love to see it on https://github.com/Quick/Quick. I don't think we have any resources to implement this on Kiwi, though -- although pull requests would be welcome.
