### ISSUE TITLE
Crash when capturing an argument that is a NSMallocBlock (works in 2.2)

### ISSUE THREAD

**Issue by CraigSiemens** [kiwi-bdd/Kiwi#360]
I've got these two methods that on the surface look like they do the same thing.

```Objective-C
- (void)callDoStuffWithBlock
{    
    [self doStuffWithBlock:^{
        [self doOtherStuff];
    }];
}

- (void)createBlockThenCallDoStuffWithBlock
{    
    void (^block)(void) = ^{
        [self doOtherStuff];
    };
    
    [self doStuffWithBlock:block];
}
```

Heres What the test looks like.
```Objective-C
it(@"should call doOtherStuff", ^{
    KWCaptureSpy *spy = [testObject captureArgument:@selector(doStuffWithBlock:) atIndex:0];

    //crashes
    //[testObject createBlockThenCallDoStuffWithBlock];

    //works
    [testObject callDoStuffWithBlock];

    void (^block)(void) = spy.argument;
    [[[testObject should] receive] doOtherStuff];
    block();
});
```

The crash (EXC_BAD_ACCESS) occurs immediately after calling `block()` but before the `it` block is finished running. Occasionally the stack trace shows `objc_storeStrong` and `objc_release` which makes me think that this could be an issue with ARC.

As far as I can tell, the only difference is the kind of block that is passed to `doStuffWithBlock:`.
`callDoStuffWithBlock` creates a `NSStackBlock`
`createBlockThenCallDoStuffWithBlock` creates a `NSMallocBlock`

**Comment by modocache** [comment]
Thanks for the report, @CraigSiemens! This issue should have been closed in after https://github.com/kiwi-bdd/Kiwi/pull/384 was merged. :)
