### ISSUE TITLE
Question about stubs on receive expectations

### ISSUE THREAD

**Issue by dmeehan1968** [kiwi-bdd/Kiwi#372]
One thing that is not all that clear in the Kiwi Wiki is regarding stubs generated for ```receive``` expectations.  

My understanding is that if you set an expectation for method call, Kiwi also stubs the call so that the underlying code does not get executed, with the logic being that you've verified that the call is made, there is no need to execute the code, which makes test execution quicker.  I can see the logic in this, but some objects need to be destroyed correctly, yet you still need to be able to test that the destruction takes place.

Take for example a ```NSTimer```.  If I want to write a test to ensure that a timer is invalidated when an object is being disposed of, or its work stopped/suspended, I might write:

```
it(@"should invalidate the timer", ^{
   [sut.myTimer should] receive] invalidate];

   [sut stop];
});
```

However, the above will cause the test suite to crash because the actual timer has not been invalidated and thus fires sometime later.

I've tried adding the following after the expectation in the hope that it would fall through to the original implementation, but this still fails in the same way, which suggests it doesn't work quite right.

```
[sut.myTimer clearStubs];
```

One workaround is to substitute the timer with a mock:

```
it(@"should invalidate the timer", ^{

   [sut.myTimer invalidate];
   sut.myTimer = [NSTimer mock];
   [[sut.myTimer stubAndReturn: theValue(YES)] isValid];
   [sut.myTimer should] receive] invalidate];

   [sut stop];
});
```

The downside is that the test code is more longwinded than strictly necessary.

There seems to be something I am missing about the automatic stubbing of method expectations, and the ability to clear the stub and allow the underlying code to be executed.

Any thoughts?

**Comment by modocache** [comment]
Thanks for the suggestion, @dmeehan1968! I agree this could be improved, either via documentation improvements or changed stub behavior. At this point, I don't think we have the resources to handle a large change to stub behavior, but if someone wanted to send a pull request with documentation updates, I'd be happy to take a look. :)
