### ISSUE TITLE
Build marked as failed when all of the tests passed

### ISSUE THREAD

**Issue by Kapin** [kiwi-bdd/Kiwi#409]
Reproduce Steps:

1. Run Kiwi Tests
2. Sometimes tests all pass and xcode declares the build failed.

Not sure if an xcode bug or Kiwi related, but I've seen multiple instances where I've had the command line indicate that every test has passed and xcode reports the build as failing. It seems random so it is difficult to reproduce.

I'll update this once I can grab a screenshot of it happening.

**Comment by sharplet** [comment]
Xcode 7? :pray: :worried:
