### ISSUE TITLE
Calling `... should] receive:...` - retains the object forever

### ISSUE THREAD

**Issue by rsaunders100** [kiwi-bdd/Kiwi#454]
Hi, I have an issue with an object being retained forever.  I expect the objects to be destroyed after the code exits the it block.  This is not the case.

    id myObject = [[MyObject alloc] init];
    id myObject2 = [[MyObject alloc] init];
                
    // Neither object is destroyed with the current code (bug I think?)
    // When this line is removed, dealloc on both objects is called (as you would expect)
    [[[myObject should] receive] doNoOpWithObject:myObject2];
                
    [myObject doNoOpWithObject:myObject2];

This is the implementation:

    @implementation MyObject
    
    - (void) doNoOpWithObject:(id)object {
    }
    - (void)dealloc {
         NSLog(@"MyObject - dealloc");
    }
    @end

**Comment by glentregoning** [comment]
I have a proposed fix in #667 which in my testing addresses the issue by releasing verifiers after running an example.

**Comment by glentregoning** [comment]
*bump*  - my PR (#667) has resolved this issue for my locally.  It would be great for this to be considered for a future Kiwi release.

**Comment by glentregoning** [comment]
*bump* Any update to reviewing my proposed fix over in #667?

**Comment by orta** [comment]
I've merged #667 - which should mean this can be closed now 👍
