### ISSUE TITLE
Build warning on 2.3.0

### ISSUE THREAD

**Issue by erikackermann** [kiwi-bdd/Kiwi#551]
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks'

**Comment by lyahdav** [comment]
Is anyone else getting a similar warning after upgrading to Xcode 7? Here's my warning:
```
directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
```

It looks to be coming from the `FRAMEWORK_SEARCH_PATHS` set by Kiwi.

I'm using Kiwi 2.4.0.
