### ISSUE TITLE
Kiwi 2.3 Property Setters are Broken

### ISSUE THREAD

**Issue by rbVessal** [kiwi-bdd/Kiwi#564]
Property setters not being recognized even if the automatically synthesized property setter or defined as one of your own.

Here is the a generic example of test code that will fail:

describe(@"beginUndo:", ^ {
it(@"should provide an empty new reloadDictionary" , ^{
[[subject should] receive:@selector(setReloadDictionary:)];
});
});

**Comment by johnMaster** [comment]
it happen to me.  
`@interface WorkFollowViewModel : NSObject  
@property (nonatomic, readwrite) NSInteger currentSection;  
@property (nonatomic, strong) NSArray * workDataSource; 
@end `  
I have only implement currentSection getter method . and then I test their setter.  
```it (@"should receive setter method", ^{  
WorkFollowViewModel *model = [[WorkFollowViewModel alloc] init];  
            [[model should] receive:@selector(setWorkDataSource:)];  
[[model should] receive:@selector(setCurrentSection:)];  
            [model saveWorkData];  
        });```
the first one receive `setWorkDataSource` is pass. But the second receive is not pass.  
it is strange. some time it also raise up `EXC_BAD_ACCESS` when I call a  test method  
`- (BOOL)saveWorkData`  
`- (BOOL)saveWorkData {  
   self.workDataSource = nil  
}`
