### ISSUE TITLE
Use XCTestExpectation

### ISSUE THREAD

**Issue by fabb** [kiwi-bdd/Kiwi#590]
Using `XCTestExpectation` makes testing of async functionality possible. There is `shouldEventually` in Kiwi, but it is not as flexible as `XCTestExpectation`.
To create a new promise with `XCTestExpectation` it is necessary to access `self` which is not possible in Kiwi AFAIK. Any ideas, workarounds.

At the moment I use `RXPromise` as a workaround, with its `runLoopWait` method I can wait for the promise to be fulfilled/rejected in a test case. I'd prefer to use `XCTestExpectation` though.

**Comment by fatuhoku** [comment]
:+1:

**Comment by sharplet** [comment]
Would you mind explaining why you feel that `expectFutureValue`/`shouldEventually` is not flexible enough?

**Comment by fabb** [comment]
Kiwi's `shouldEventually` polls for the expected value until timeout. In several cases, I want to execute something asynchronously, and when finished (successfully or not), I want to do several checks on it. And if the asynchronous task fails, I want the unit test to fail fast and not wait until timeout.

Consider this example borrowed from NSHipster:

```
it(@"async test", ^{
    NSURL *URL = [NSURL URLWithString:@"http://nshipster.com/"];
    NSString *description = [NSString stringWithFormat:@"GET %@", URL];
    XCTestExpectation *expectation = [self expectationWithDescription:description];

    NSURLSession *session = [NSURLSession sharedSession];
    __block NSData *pData = nil;
    __block NSURLResponse *pResponse = nil;
    __block NSError *pError = nil;
    NSURLSessionDataTask *task = [session dataTaskWithURL:URL
                                        completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
                                            pData = data;
                                            pResponse = response;
                                            pError = error;
                                            [expectation fulfill];
                                        }];

    [task resume];

    [[pError should] beNil];
    [[pData shouldNot] beNil];
    [[pResponse shouldNot] beNil];
    [[pResponse should] beKindOfClass:[NSHTTPURLResponse class]];
    [[theValue([(NSHTTPURLResponse *)pResponse statusCode]) should] equal:theValue(200)];
    [[pResponse.URL.absoluteString should] equal:URL.absoluteString];
    [[pResponse.MIMEType should] equal:@"text/html"];

    [self waitForExpectationsWithTimeout:task.originalRequest.timeoutInterval handler:^(NSError *error) {
        [task cancel];

    }];
});
```

**Comment by tsabend** [comment]
+1 Running into problems with Kiwi + OHHTPPStub https://github.com/AliSoftware/OHHTTPStubs/wiki/OHHTTPStubs-and-asynchronous-tests

**Comment by modocache** [comment]
Thanks for the idea, @fabb! This would be cool, and has been discussed on other testing/expectation frameworks: https://github.com/Quick/Nimble/issues/28. My thoughts, echoed in that pull request, is that `XCTestExpectation` has too many restrictions -- it requires the current `XCTestCase` to vend expectations, it has very specific usages in mind that don't play well with dynamically generated tests, and so on.

Closing this for now -- we probably don't have the resources to really explore this idea further, even if it was something we wanted.
