### ISSUE TITLE
The Getting Started with Kiwi 2.0 link is invalid.

### ISSUE THREAD

**Issue by wongzigii** [kiwi-bdd/Kiwi#608]
http://editorscut.com/Books/001kiwi/001kiwi-details.html Show the 404 page.

**Comment by modocache** [comment]
Yup, looks like the link on https://github.com/kiwi-bdd/Kiwi/wiki/Getting-Started-with-Kiwi-2.0 for "the Kiwi Book by Daniel Steinberg" points to http://editorscut.com/Books/001kiwi/001kiwi-details.html, which isn't a valid link anymore. @dimsumthinking, what's the best thing to link to here?

**Comment by dimsumthinking** [comment]
Thanks for asking - 

The book isn’t being maintained so I’ve just modified the price so it is available for free at https://itunes.apple.com/us/book/test-driving-ios-development/id502345143?ls=1&mt=11 <https://itunes.apple.com/us/book/test-driving-ios-development/id502345143?ls=1&mt=11>

I do intend to write a book at some point about Quick

Enjoy,

Daniel

**Comment by modocache** [comment]
Coolio! Thanks! I updayed the book link on the wiki :raised_hands: 

Thanks again, @wongzigii! :+1:
