### ISSUE TITLE
Running a single KIWI spec with xctool

### ISSUE THREAD

**Issue by mohjay** [kiwi-bdd/Kiwi#614]
Hi,

Has anyone been able to successfully pass the KW_SPEC variable to xctool. I'm trying to run a single KIWI spec by using https://github.com/kiwi-bdd/Kiwi/wiki/Kiwi-FAQ#q-how-do-i-run-a-single-spec-describecontextit.

I can run all the tests successfully with xctool but it doesn't seem to pick up the KW_SPEC value. I've tried it in a lot of different places with the command line but no luck.

e.g. xctool -destination 'platform=iOS Simulator,name=iPad Retina,OS=latest' -sdk iphonesimulator -workspace SampleProject.xcworkspace -scheme SampleProject KW_SPEC=NewAssessmentTests.m:12 test -only SampleProject_Acceptance_Tests

Using Kiwi v2.3.1
Using xctool 0.2.3

Cheers,
Mo

**Comment by ohadschn** [comment]
I can't get it to work either. I placed a bounty on your StackOverflow question: http://stackoverflow.com/questions/30387123/running-a-single-kiwi-spec-with-xctool

**Comment by modocache** [comment]
I'm merging this issue with #655. See @sharplet's comment there -- it would be nice to support this, and we'd be willing to look at a pull request if you think it'd still be valuable.
