### ISSUE TITLE
Test target not found for iOS 7. Succeeds on iOS 8 simulators.

### ISSUE THREAD

**Issue by adongarwar** [kiwi-bdd/Kiwi#615]
Following the documentation, i created i installed Kiwi and created test targets which are passing sample test successfully but for some reason, test target is not found on iOS 7.0. Please find logs as follows -

IDEBundleInjection.c: Error 3588 loading bundle '/Users/adongarwar/Library/Developer/Xcode/DerivedData/Carebook-dhsnptnrtmdyhbhdsghzjbnziikm/Build/Products/Distribution-AdHoc-iphonesimulator/CarebookTests.xctest': The bundle “CarebookTests” couldn’t be loaded.
DevToolsBundleInjection environment:
XCInjectDiagnostics: (null)
XCInjectBundleInto: /Users/adongarwar/Library/Developer/Xcode/DerivedData/Carebook-dhsnptnrtmdyhbhdsghzjbnziikm/Build/Products/Distribution-AdHoc-iphonesimulator/CB Trunk.app/CB Trunk
XCInjectBundle: /Users/adongarwar/Library/Developer/Xcode/DerivedData/Carebook-dhsnptnrtmdyhbhdsghzjbnziikm/Build/Products/Distribution-AdHoc-iphonesimulator/CarebookTests.xctest
TestBundleLocation: /Users/adongarwar/Library/Developer/Xcode/DerivedData/Carebook-dhsnptnrtmdyhbhdsghzjbnziikm/Build/Products/Distribution-AdHoc-iphonesimulator/CarebookTests.xctest
TMPDIR: /Users/adongarwar/Library/Developer/CoreSimulator/Devices/6747FF21-77A9-423E-A778-AC0B8FDBE606/data/Applications/7789EE25-B2B3-4080-A0FE-5D66E2C6E506/tmp
DYLD_LIBRARY_PATH: /Users/adongarwar/Library/Developer/Xcode/DerivedData/Carebook-dhsnptnrtmdyhbhdsghzjbnziikm/Build/Products/Distribution-AdHoc-iphonesimulator
DYLD_INSERT_LIBRARIES: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/IDEBundleInjection.framework/IDEBundleInjection
DYLD_FRAMEWORK_PATH: /Users/adongarwar/Library/Developer/Xcode/DerivedData/Carebook-dhsnptnrtmdyhbhdsghzjbnziikm/Build/Products/Distribution-AdHoc-iphonesimulator
DYLD_FALLBACK_LIBRARY_PATH: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_FALLBACK_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks

**Comment by sharplet** [comment]
Thank you for taking the time to file a report! However, this doesn't immediately appear to be a Kiwi-specific problem, so closing for now.

Is this occurring in a brand new project where you're install Kiwi for the first time? If this issue is reproducible in a completely fresh project after installing Kiwi, please respond and we can reopen the issue. Without a reproduction case we won't be able to debug the issue.

**Comment by adongarwar** [comment]
Never mind. Issue was, when i did pod update for kiwi on an existing project, the min deployment target set for test target was iOS 8.0. I changed it manually to iOS 7.0 and thing worked. Pos installation shud have done it automatically.

**Comment by sharplet** [comment]
Great! :+1:
