### ISSUE TITLE
unable to build for framework

### ISSUE THREAD

**Issue by guiduroy** [kiwi-bdd/Kiwi#616]
i get the following error when building the project: 

Check dependencies
No architectures to compile for (ARCHS=i386 x86_64, VALID_ARCHS=arm64 armv7 armv7s).

**Comment by sharplet** [comment]
Hi, and thanks for the report! Sorry for the delayed reply.

Is this still an issue for you? Are you trying to build the Kiwi project directly, or are you using Kiwi via CocoaPods, or some other means? Do you have a link to a project that reproduces your problem?

I'm going to go ahead and close this for now, as there's not much for me to go on. If you have any more info or it's still a problem, feel free to reopen the issue.
