### ISSUE TITLE
Slightly ambiguous let() wiki documentation.

### ISSUE THREAD

**Issue by dtrenz** [kiwi-bdd/Kiwi#617]
In the Wiki, `let` is described as:

> let(subject, aBlock) declares a local helper variable that is re-initialized before every example.

I have a few questions based on this description:
1. Is "example" synonymous with `it` block?
2. Is the execution of a `let` limited to the context it is in, as well as all sub-contexts (just like beforeEach)?

My understanding of how `let` works is that this test code...

```obj-c
context(@"given a context", ^{
    let(someMock, ^id{
        return [some nullMock];
    });
});
```

...is equivalent to this test code:

```obj-c
context(@"given a context", ^{
    __block id someMock;

    beforeEach(someMock, ^id{
        someMock =  [SomeClass nullMock];
    });
});
```

Is this accurate?

**Comment by sharplet** [comment]
Yep, that's the intended use case. Just like a `beforeEach`, `let` variables are reinitialised before each example (i.e., `it` block) runs.

Closing this for now. If there's anything further you'd like to clarify, please ask!

**Comment by dtrenz** [comment]
Thanks!
