### ISSUE TITLE
[[object shouldNot] beNil] never fails

### ISSUE THREAD

**Issue by karstenBriksoft** [kiwi-bdd/Kiwi#618]
I was just writing some tests and noticed that [[anObject shouldNot] beNil] cannot fail and thus should always fail with a warning that it should not be used.

Background:
if object is nil, shouldNot is not sent and the result is again nil. beNil is then also not sent and no error is created.

Possible fix:
object could be wrapped in a macro like possiblyNil(object) and only if that macro was used, shouldNot beNil will not raise an exception. That still doesn't fix the problem that nil doesn't respond to any method properly but at least the user is made aware of the problem.

**Comment by sharplet** [comment]
Hi, thanks for the report! However I don't believe this should be an issue:

<img width="660" alt="screen shot 2015-08-03 at 8 40 13 pm" src="https://cloud.githubusercontent.com/assets/147686/9035937/e5e470a2-3a1f-11e5-953a-cc7f661d60e8.png">

This spec fails, as expected:

```objc
#import <Kiwi/Kiwi.h>

SPEC_BEGIN(KWNilMatcherTests)

describe(@"shouldNot beNil", ^{
    it(@"can fail the tests", ^{
        [[(id)nil shouldNot] beNil];
    });
});

SPEC_END
```

If you're seeing this issue in practice, please check that you're running the latest version of Kiwi and if you could, provide a link to a project that reproduces the issue.
