### ISSUE TITLE
A crash in the test suite forces the whole suite to be re-run in the future

### ISSUE THREAD

**Issue by michaeleiselsc** [kiwi-bdd/Kiwi#619]
When a crash occurs during testing, it causes the next round of testing to run all tests in the project, even if only the play button for a single file is clicked to run that file only. This is very time-consuming, as my project has many tests across the project.

**Comment by sharplet** [comment]
Hi, thanks for the report! The way I see it there's probably two likely causes: a) this is an issue with Xcode/XCTest and runtime test case generation, or b) Kiwi has a bug. Currently I'm inclined to think it's the former, but the best way to validate that would probably be to work out if other testing frameworks similar to Kiwi have the same problem.

@modocache have you seen this kind of thing on Quick?

**Comment by michaeleiselsc** [comment]
@sharplet I should've been more clear: it's not just after a crash, it's after a clean and rebuild and other  cache invalidations.

After looking into the issue more, it appears that prior to running the test suite, Xcode doesn't see any methods for any of the test cases, I would assume because of Kiwi's unusual syntax. So when you run the tests, it is first figuring out what tests are in these actual files and running the tests. Then when you run a later test, it already knows what methods there are and so it doesn't seem to mind just testing one file. This is speculation.

**Comment by michaeleiselsc** [comment]
You can tell this because when you click the arrow to expand the tests for a given file, when looking in the test navigator, no methods are shown until after you run the full test suite.

**Comment by sharplet** [comment]
This really seems to me like an XCTest / Xcode test navigator issue. This isn't really something we can fix in Kiwi unfortunately. If this is still an issue for you, I'd recommend you file a radar.
