### ISSUE TITLE
Kiwi 2.4.0

### ISSUE THREAD

**Issue by sharplet** [kiwi-bdd/Kiwi#623]
With [shared example groups](https://github.com/kiwi-bdd/Kiwi/pull/600) and [Carthage support](https://github.com/kiwi-bdd/Kiwi/pull/611) being merged, I think it's about time to roll a new version.

@kiwi-bdd/core-team I'm happy to take care of this, but I'll need access to push the podspec first!

**Comment by supermarin** [comment]
Hey @sharplet, I've added you to the trunk, and you should have all the permissions to publish new Kiwies now.

**Comment by sharplet** [comment]
Woo :tada: 

I might actually reopen this one for the time-being until 2.4 is officially tagged and pushed.
