### ISSUE TITLE
Stepping down

### ISSUE THREAD

**Issue by supermarin** [kiwi-bdd/Kiwi#624]
Hey @kiwi-bdd/core-team, it's been awhile since I was able to contribute something sane to Kiwi.
As we're not using Kiwi on work, I find it hard to come back and switch contexts.

I'll still be here and happy to answer questions, just don't want people to expect from me to fix things.
Thank you everyone for spending your time on this, it's been quite a project.

**Comment by modocache** [comment]
Thanks for all your help, @supermarin!! :wave:

**Comment by sharplet** [comment]
Thanks @supermarin! ✨❤️
