### ISSUE TITLE
How to test individual file?

### ISSUE THREAD

**Issue by sundeepgupta** [kiwi-bdd/Kiwi#625]
When I click on the diamond in the gutter, I'm expecting only that file to run. However, the entire suite runs.

**Comment by sharplet** [comment]
Thanks for the report! I believe I've observed similar behaviour before, too. I have a couple of questions:

- Which version of Xcode / OS X are you using?
- Does the whole suite run again if you click in the gutter a second time?

**Comment by sundeepgupta** [comment]
Thanks for responding. It is working properly. The diamond is only running that particular file. I could have sworn it was always running the entire suite, but I've been wrong many times before. Thanks.

**Comment by lyahdav** [comment]
I have a recurring intermittent issue where clicking the diamond in the gutter in a file will run the entire suite. Should I open a new issue?
This is Xcode 7.0 (happened on latest Xcode 6.x as well), OS X 10.10.5.
If I click on the gutter a second time it will sometimes run the whole suite, sometimes just that file.
