### ISSUE TITLE
Getting Started Guide is over-complex, and out-of-date

### ISSUE THREAD

**Issue by Drarok** [kiwi-bdd/Kiwi#626]
> The goal is to provide a BDD library that is exquisitely simple to setup and use.

The [getting started docs][kiwi getting started] are _not_ a simple guide, there's even quotes throughout saying "this part is tricky", "also tricky"!

> I'm going to be frank. I have no idea what you are going to see here - depending on the Create Your Own Adventure path you used to get here, there may be one or several schemes listed here[…]

This does _not_ fill me with confidence.

Also, the docs repeatedly state how to do something, then contradict this for Xcode 5 (and up, presumably). Xcode 5.0 was released on September 18, 2013, and Xcode 6 was released on September 17, 2014.

[kiwi getting started]: https://github.com/kiwi-bdd/Kiwi/wiki/Getting-Started-with-Kiwi-2.0

**Comment by sharplet** [comment]
I think you're exactly right! It's about time Kiwi's docs had a fresh overhaul.

Is this something you'd be interested in contributing?

**Comment by Drarok** [comment]
@sharplet: I can help with proofreading and testing out the steps to see if they work, but alas I am a _terrible_ writer. Also, I don't know this project very well at all – I'm currently in the stages of mapping out what options there are for testing before choosing one.

**Comment by sharplet** [comment]
So I've just updated the readme to _not_ point to the terrible instructions anymore: https://github.com/kiwi-bdd/Kiwi/commit/d291b7f4ccc13eca49a61ebe45d97592de2aed91.

**Comment by modocache** [comment]
Thanks for bringing this up, @Drarok, and thanks for the updates, @sharplet! If there are additional errors/improvements here, please feel free to open a pull request.
