### ISSUE TITLE
Say goodbye to theValue()?

### ISSUE THREAD

**Issue by sharplet** [kiwi-bdd/Kiwi#627]
The question was asked by jwong on the mailing list: https://groups.google.com/d/msg/kiwi-bdd/amO_F_PV-5c/ofjYHLcxJgAJ.

> Why do we use theValue( ) instead of auto boxing? @( )?
>
> Seems more succinct to use @( ).

I'm inclined to agree, but I think it needs further consideration:

- Are there advantages `theValue()` gives us that Objective-C literals don't offer? (Maybe something to do with C structs? ¯\\\_(ツ)\_/¯)
- We'd be breaking a _lot_ of tests. Is that worth the pain?

**Comment by ecaselles** [comment]
I would not remove/deprecate `theValue()` straight away, since a lot of existing test suites are relying on it :crying_cat_face:. But I think it is a good idea to support auto boxing :+1:. Therefore, I would add it first and in a few months re-evaluate if `theValue()` should be deprecated.

**Comment by sharplet** [comment]
I'm going to make a call that introducing a massive breaking change like this isn't worthwhile. Closing for now.
