### ISSUE TITLE
Make expectations on argument types

### ISSUE THREAD

**Issue by lyahdav** [kiwi-bdd/Kiwi#634]
When using `[[subject should] receive:@selector(aSelector) withArguments:...]` I sometimes don't care what exactly an argument is, but I care about its type. I'd like to say something like:
`[[subject should] receive:@selector(aSelector) withArguments:any([Foo class])]`. I know you can do this with a `KWCaptureSpy` but it seems much more natural to have a construct like `any([Foo class])` since we already have `any()`.

**Comment by modocache** [comment]
Thanks for the idea, @lyahdav! This would certainly be nice to have. :)

@sharplet and I are trying to do some spring cleaning on open Kiwi issues -- I'm going to close this for now, but if you're interested in contributing this, please send a pull request!
