### ISSUE TITLE
Test is always passing if running the individual file only. 

### ISSUE THREAD

**Issue by sundeepgupta** [kiwi-bdd/Kiwi#645]
If I run the entire test suite, every spec runs fine. If I run an individual file, all the specs always pass and the console shows "(null)" for each spec. 

For example, this spec:

```
#import "Kiwi.h"

SPEC_BEGIN(INFN_Spec)

describe(@"bla", ^{
    it(@"random", ^{
        [[@1 should] equal:@2];
    });
});

SPEC_END
```

Shows this in the console:

```
Test Suite 'Selected tests' started at 2015-09-17 10:20:13.483
Test Suite 'INFN_Spec' started at 2015-09-17 10:20:13.483
Test Case '-[INFN_Spec (null)]' started.
Test Case '-[INFN_Spec (null)]' passed (0.002 seconds).
Test Suite 'INFN_Spec' passed at 2015-09-17 10:20:13.486.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.003) seconds
Test Suite 'Selected tests' passed at 2015-09-17 10:20:13.486.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.004) seconds
```

I'm running Kiwi 2.4.0 on Xcode 7.1 Beta.

**Comment by kanstantsin** [comment]
+1
Can't run individual file tests on Xcode 7.

**Comment by PetarBel** [comment]
The same problem for me. However, even if I run all tests I can observe the same behaviour. Strangely though, tests work as expected the first time they are run, and things gets messed up on a subsequent run. iOS 9, XCode 7

**Comment by priteshshah1983** [comment]
+1

**Comment by haifengkao** [comment]
+1

**Comment by lyahdav** [comment]
I think this is the same issue I just commented on here: https://github.com/kiwi-bdd/Kiwi/issues/625#issuecomment-144535569

**Comment by Lyricalpanda** [comment]
This is happening for all tests for me for X amount of time after I run the tests. It happens regardless of if it's the individual class or the full test cases. If I switch schemas, it works for the first time, then I get nulls on all of my tests.

Only thing that seems to fix it is to force quit XCode. It's kind of unacceptable.

**Comment by yas375** [comment]
We are having same issue. Running tests in a single file and it always reports that 1 test has passed, but it doesn't actually executes the tests.

**Comment by cryptojuice** [comment]
+1

**Comment by mmesutt** [comment]
+1

**Comment by alekoleg** [comment]
+1

**Comment by EvanLee** [comment]
+1   The same problem for me。 I must rename the spec name to go on work when this issue happened
![image](https://cloud.githubusercontent.com/assets/6031217/13593964/5f219870-e53b-11e5-9cfe-82d687be7e81.png)

**Comment by sharplet** [comment]
Hi! Thanks for the issue. At this point our stance is to always run the entire test suite. There are long-standing issues with test navigator integration that are not specific to Kiwi and are also experienced by other testing frameworks that dynamically build test invocations.

@modocache and I are doing spring cleaning on issues at the moment, so I'm going to close this for now.

**Comment by iamprabal** [comment]
Is this resolved in a newer version? I started with Kiwi just a month back, having already had a huge iOS codebase written in ObjC, thus I have a mammoth task of writing a lot of test cases on existing codebase. It would have been really very very helpful if I could just run one spec file at a time and not the whole suite of tests.

**Comment by Lyricalpanda** [comment]
I would highly recommend not using Kiwi if you're doing your test cases from scratch. The last commit was 8 months ago and this issue hasn't been resolved, according to this open ticket from 2017: https://github.com/kiwi-bdd/Kiwi/issues/689

**Comment by iamprabal** [comment]
@Lyricalpanda do you recommend one of Quick or Specta instead? From what I could read online, Quick is useful for swift based codebase and Kiwi seemed to be the more popular choice for ObjC, though I am not sure how it'll compare to Specta? Do you have a recommendation?
