### ISSUE TITLE
Allow KW_SPEC to specify spec name

### ISSUE THREAD

**Issue by ohadschn** [kiwi-bdd/Kiwi#655]
I understand that the current `<file name>:<line number of spec>` syntax allows for flexibility regarding the scope of the tests that run (spec/describe/context/it) but at best, it is unreliable. I couldn't get it to work at all, and even if I did it would be broken the first time someone added or deleted a single line of code.

However the spec name is pretty well defined. If I could say `KW_SPEC=FooSpec` that should be pretty reliable (unless I rename the spec of course, but I guess there's an inherent limit to this method).

**Comment by sharplet** [comment]
Hi! Thanks for opening an issue. If this is something that you would still find useful and isn't too big of a change, we may consider a pull request for a change like this.

@modocache and I are doing spring cleaning on issues at the moment, so I'm going to close this for now. Feel free to comment if you'd like to discuss this further though!
