### ISSUE TITLE
Got EXC_BAD_ACCESS when use_framework! is in pods

### ISSUE THREAD

**Issue by sanatory** [kiwi-bdd/Kiwi#665]
1.  Add Kiwi via cocoapods, currently have v2.4.0, have use_frameworks! in the podfile
2. Try to run tests 
![screen](https://cloud.githubusercontent.com/assets/14928532/11746617/d4dfa99a-a016-11e5-91b3-63247bfabdad.png)

**Comment by action456789** [comment]
I do as follows:  
Ensure that "Test Host" is is set to $(BUNDLE_LOADER). This specifies the executable that the unit tests will be injected into. We make it match the value of the "Bundle Loader" setting. (Note that this step is not necessary if your target is a static library – you can leave this field blank.)

**Comment by sanatory** [comment]
it doesn't help, still the same issue

**Comment by sharplet** [comment]
Hi! Thanks for opening an issue. If this is still a problem, would it be possible for you to provide a code sample that reproduces the problem? Can you reproduce the crash in a brand new project?

I'm going to close this for now, but please feel free to comment and we can reopen this if it's still a problem!
