### ISSUE TITLE
Rare should equal failure with dictionary comparison

### ISSUE THREAD

**Issue by lolgear** [kiwi-bdd/Kiwi#668]
I have a dictionary equality (`[[one should] equal:two]`).

And sometimes this equality failed.

I look through the dictionaries and can't find any differences.

Then I rerun tests and everything fine.

**Comment by modocache** [comment]
@lolgear Thanks for the report! Does this problem still occur? It would be great if you could reduce this down to a smaller test case -- this is the first I've heard of an issue like this with Kiwi, so I wonder if maybe you have a race condition, or some other mutating state, in your tests?

@sharplet and I are trying to do some spring cleaning on open Kiwi issues. We care about fixing this if it's a problem, but I'll close this issue until we hear back from you. :)
