### ISSUE TITLE
Tests crashing after Swift 2.2 update

### ISSUE THREAD

**Issue by eduardoeof** [kiwi-bdd/Kiwi#670]
Hi,

Today I updated my Xcode to 7.3 (Swift 2.2) and some of my Kiwi tests crashed. I noticed that several (not all) `[[sut should] receive:...` assertions are crashing, but in Xcode 7.2.1 were ok. Do you have any guess?

**Comment by rjoudrey** [comment]
Are you launching the tests via ⌘U or by clicking the play button on the test?

**Comment by eduadroeof** [comment]
Via ⌘U. I'm using now Xcode 7.2.1 again and they are working normally.

**Comment by rjoudrey** [comment]
They work for me in Xcode 7.3

**Comment by modocache** [comment]
@eduardoeof Could you post the stack trace, so we could help diagnose the issue?
