### ISSUE TITLE
Kiwi is not in use?

### ISSUE THREAD

**Issue by walkdianzi** [kiwi-bdd/Kiwi#674]
OCUnit and the SenTestingKit framework are deprecated and  removed from Xcode. So Kiwi is not in use?

![2016-05-03 8 02 29](https://cloud.githubusercontent.com/assets/5734867/14982593/055d3cb2-116a-11e6-88bf-be1c9dcf3a1d.png)

**Comment by sharplet** [comment]
Kiwi dropped support for OCUnit some time ago. If you have a specific problem, please feel free to open an issue!
