### ISSUE TITLE
Book not available in my country

### ISSUE THREAD

**Issue by bimawa** [kiwi-bdd/Kiwi#675]
Guys i'm very much want read Test Driving iOS Development with Kiwi
 book. But i can't get it in my country. Maybe someone have it and can share it?

**Comment by sharplet** [comment]
That's a shame, I hope you can get access to the book somehow. Unfortunately, the book isn't really affiliated with the kiwi-bdd GitHub org, so there's nothing we can do for you here. My guess is that it would be best to try reaching out directly to the author.

**Comment by bimawa** [comment]
Ohh so sad, i talk with author he can't help me too. Ok i use my Hacks skills for get this book.
