### ISSUE TITLE
Swift 3 cocoapods run failed

### ISSUE THREAD

**Issue by mihailsalari** [kiwi-bdd/Kiwi#691]
Swift 3 cocoapods run failed

**Comment by orta** [comment]
Please give a more instructive issue - reproduction steps, sample apps ect.

**Comment by mihailsalari** [comment]
Why this issue is closed? You resolve it?

**Comment by mihailsalari** [comment]
Try to install that framework via Xcode 8 and import it. You will see the error. Swift project
