### ISSUE TITLE
kiwi report error that' SenTestingKit/SenTestingKit.h  file not found'

### ISSUE THREAD

**Issue by DreamOfXM** [kiwi-bdd/Kiwi#695]
I search in the internet and konw that  SenTestingKit framwork is depreated，but you do not remove it from kiwi. when I run your progect ,it show a large piece of red error.I wondered if you were not maintaining it in the future?

**Comment by orta** [comment]
SenTestingKit was never shipped with Kiwi, it came with Xcode 4.x - and was replaced by XCTest by 5.x and onwards. You'll need to update Kiwi if you are moving Xcode versions.

**Comment by DreamOfXM** [comment]
I insatall your kiwi through pod kiwi,but install wrong version.I hope you can resolve it
