### ISSUE TITLE
build synthetic seismogram in a specific station

### ISSUE THREAD

**Issue by alirezaniki** [kiwi-bdd/Kiwi#696]
Hi everyone
I have to have a script that read :

(1) source latitude, longitude, depth, and fault parameters e.g., strike, rake, dip, length of fault, M0 etc

(2) station coordinate e.g., latitude, longitude

(3) velocity model

then create synthetic seismogram at that station. Do you have such script or can you give me some hints how can I do it using KIWI.
many thanks

**Comment by orta** [comment]
This is the wrong repo for that, this is an objective-c test runner for macOS and iOS projects. I did a quite googling but don't really know where to refer you. Good luck.
