### ISSUE TITLE
Preparing next release

### ISSUE THREAD

**Issue by ecaselles** [kiwi-bdd/Kiwi#699]
I would like to push a new release of Kiwi out to include what it is currently on master, plus the fixes needed to ensure compatibility with Xcode 9 (which we are currently working on).

Initially, the work included in this milestone would be:

- [x] Everything already merged to master since 2.4.0 (see [diff](https://github.com/kiwi-bdd/Kiwi/compare/v2.4.0...master))
- [x] Fixing CI builds (#703)
- [x] Fixing #698: renaming the `any` macro
- [x] Ensure compatibility with Xcode 9 (no warnings)
- [ ] Release new version

I know there were [conversations](https://github.com/kiwi-bdd/Kiwi/issues/662#issuecomment-223775644) for the next release to be v3.0, but it feels like a minor version bump could be more appropriate, since most of the changes added are bug fixes, memory management improvements and other maintenance work. 

@kiwi-bdd/core-team would you be happy for me to tag this release as v2.4.1 or would you rather continue with the plan of naming it v3.0 just for closure?

**Comment by orta** [comment]
Dang, yeah, that's 2 years worth of PRs, should probably do it at 2.5 if there's no source breaking changes

**Comment by ecaselles** [comment]
Thanks @orta, happy to go with 2.5 👍

The only breaking change might the one we are about to introduce to fix #698. 🙏 leave any suggestions there if you think there is a way to fix it without breaking previous versions.

**Comment by grevolution** [comment]
any update on #698

**Comment by scottdensmore** [comment]
What is the plan for getting Xcode 9 support? Is this something that is going to be done?

**Comment by ecaselles** [comment]
Yes @scottdensmore. I will have a look at the work done by @SevInf and hopefully will try to get the new build out before the end of the year

**Comment by scottdensmore** [comment]
Thanks @ecaselles. Anything we can do to help?

**Comment by ecaselles** [comment]
@scottdensmore I am currently reviewing the two PRs opened by @SevInf and hoping to get a green build. Not sure about #701, looks like if we can't keep backwards compatibility, it is just not a minor version bump.

**Comment by ecaselles** [comment]
FYI I will be tagging this release as 3.0, as it will introduce a breaking changes (#701)
