### ISSUE TITLE
XCTest.framework/XCTest' does not contain bitcode

### ISSUE THREAD

**Issue by PatrickDotStar** [kiwi-bdd/Kiwi#707]
Using Kiwi 3.0.0

When trying to run the Unit Tests on a real device, Xcode trows an error saying `You must rebuild it with bitcode enabled`. Running the tests on simulator works fine.
Nimble had a similar [issue](https://github.com/Quick/Nimble/issues/170). They way I solved this is setting the `ENABLE_BITCODE` to `NO` using cocoapods

```		
if ['Kiwi'].include? target.name
	target.build_configurations.each do |config|
		config.build_settings['ENABLE_BITCODE'] = 'NO'		
       end
end
```

`ld: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' for architecture arm64`

Is Bitcode actually really required?

**Comment by haifengkao** [comment]
to make PatrickDotStar's answer for clear
add the following to the Podfile
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Kiwi'].include? target.name
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
  end
end
```

**Comment by amir-majidi** [comment]
go to your target name => build setting=> EnableBitcode  
change the value to no
