### ISSUE TITLE
Oops… the system encountered a problem (#500) - Retrying in X:XXs…

### ISSUE THREAD

**Issue by xpolb01** [kiwi-bdd/Kiwi#711]
When having multiple accounts Kiwi displays a following message for two of them. The one that I've logged into first is fine:
<img width="991" alt="screen shot 2018-08-03 at 1 43 33 pm" src="https://user-images.githubusercontent.com/13209628/43639146-efd5ecbc-9723-11e8-8a81-504ad6517fbe.png">
It's will disappear if you will right click and click reload.

**Comment by orta** [comment]
This is the wrong repo, you want kiwi for Gmail
